#!/usr/bin/env python3
"""Regression tests for YAML-safe frontmatter (validate-okf.py rule 5).

Ingestion is model-driven: the ingest skill mirrors the shape of
templates/*.md, so an unsafe free-text scalar is a matter of when, not if.
Three distinct failure modes follow, and before rule 5 existed
validate-okf.py caught none of them — it checked `type:` with a regex and
never parsed YAML, so a syntactically destroyed block passed:

  1. unquoted value containing `: `  — safe_load raises; build-index.py falls
     back to its naive parser and the entity hub's auto-facts block empties.
  2. unquoted value containing ` #`  — parses FINE, value silently truncated
     at the hash. No exception, nothing in the manifest to grep for.
  3. quoted value with unescaped inner quotes — same as (1), but the value IS
     quoted. This is what a model writes once told to quote but not to escape,
     which is why quoting the templates is necessary but not sufficient.

What these tests pin down, in order of what actually protects the bundle:

  a. all three modes FAIL validate-okf.py, each localized to its line and kind
  b. safe shapes are NOT flagged — including trailing comments on enum/date
     fields, which our own templates use. A check that cries wolf on nearly
     every file gets ignored, so this is as load-bearing as (a).
  c. the four shipped templates scan clean (entity.md once shipped a
     placeholder whose own text contained `: `)
  d. `--fix` repairs all three preserving inner quotes, and revalidates clean
  e. end-to-end: a broken fact no longer silently empties the hub, and after
     `--fix` + rebuild the description in the manifest is intact
  f. missing PyYAML warns on stderr instead of switching parsers in silence

Pure stdlib, Python 3.10+, same scaffolding style as tests/test_index.py:
throwaway bundles under a tempdir, shipped scripts driven via subprocess.

Exit code 0 only if every check passes.
"""
import datetime
import importlib.util
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import traceback
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
ASSETS = REPO_ROOT / "plugin" / "assets"
TODAY = datetime.date.today().isoformat()
FM_RE = re.compile(r"\A---\s*\n(.*?)\n---\s*\n", re.DOTALL)

# A few assertions describe what PyYAML does with a given block (raising on
# mode 1/3, truncating on mode 2). Those are meaningless where PyYAML is absent,
# because then every file takes the naive parser instead — so they are skipped
# rather than asserted, and the skip is printed rather than swallowed.
try:
    import yaml  # noqa: F401
    HAS_YAML = True
except ImportError:
    HAS_YAML = False

checks = []
skipped = []


def record(label, passed, detail=""):
    checks.append((label, passed))
    print(f"[{len(checks):2d}] {'PASS' if passed else 'FAIL'} — {label}")
    if detail and not passed:
        for ln in str(detail).splitlines():
            print(f"       {ln}")
    return passed


def skip(label, why):
    skipped.append((label, why))
    print(f"[--] SKIP — {label} ({why})")


def guarded(fn, *a):
    try:
        fn(*a)
    except Exception:
        record(f"{fn.__name__} raised", False, traceback.format_exc())


def run_script(bundle, script_name, args=None, block_yaml=False):
    """Drive a shipped script in `bundle`. With block_yaml, PYTHONPATH gains a
    `yaml.py` that raises ImportError on execution, which is indistinguishable
    from PyYAML being absent — the state that makes every file take the naive
    parser and turns a per-file bug into a bundle-wide one."""
    env = dict(os.environ)
    if block_yaml:
        shim = bundle / "_noyaml"
        shim.mkdir(exist_ok=True)
        (shim / "yaml.py").write_text(
            'raise ImportError("simulated: PyYAML absent")\n', encoding="utf-8")
        env["PYTHONPATH"] = str(shim)
    return subprocess.run(
        [sys.executable, str(bundle / "scripts" / script_name)] + (args or []),
        cwd=str(bundle), capture_output=True, text=True, encoding="utf-8", env=env,
    )


def new_bundle(root, name):
    bundle = root / name
    (bundle / "scripts").mkdir(parents=True, exist_ok=True)
    for f in ("build-index.py", "briefing.py", "validate-okf.py"):
        shutil.copy2(ASSETS / "scripts" / f, bundle / "scripts" / f)
    (bundle / "knowledge").mkdir(parents=True, exist_ok=True)
    (bundle / "knowledge" / "log.md").write_text("# Log\n", encoding="utf-8")
    return bundle


MARKER = (
    "\n<!-- BEGIN auto-facts -->\n"
    "<!-- Regenerated by scripts/build-index.py — do not edit by hand. -->\n"
    "<!-- END auto-facts -->\n"
)

ENTITY_LINK = "/entities/person/angelo.md"


def write_entity(bundle, rel=ENTITY_LINK.lstrip("/")):
    (bundle / "knowledge" / rel).parent.mkdir(parents=True, exist_ok=True)
    (bundle / "knowledge" / rel).write_text(
        "---\n"
        "type: entity\n"
        "kind: person         # person | org | project | tool | concept\n"
        'title: "Angelo Spinardi"\n'
        'description: "engineer on the export team"\n'
        "aliases: []\n"
        f"created: {TODAY}\nupdated: {TODAY}\n"
        "---\n\nAngelo.\n" + MARKER,
        encoding="utf-8")


def write_fact(bundle, rel, description_line, occurred=TODAY):
    """`description_line` is injected verbatim so a test can plant a raw,
    deliberately unsafe line — quoting it here would defeat the point."""
    path = bundle / "knowledge" / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "---\n"
        "type: fact\n"
        f"{description_line}\n"
        f"entities: ['{ENTITY_LINK}']\n"
        "status: active       # active | deprecated | superseded\n"
        f"occurred: {occurred}\nupdated: {occurred}\n"
        "---\n\nBody.\n",
        encoding="utf-8")
    return path


def load_validator():
    spec = importlib.util.spec_from_file_location(
        "okf_validator", ASSETS / "scripts" / "validate-okf.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def manifest_rows(bundle):
    p = bundle / "knowledge" / "manifest.jsonl"
    return [json.loads(ln) for ln in p.read_text(encoding="utf-8").splitlines() if ln.strip()]


def auto_facts_block(bundle, rel=ENTITY_LINK.lstrip("/")):
    text = (bundle / "knowledge" / rel).read_text(encoding="utf-8")
    m = re.search(r"<!-- BEGIN auto-facts -->(.*?)<!-- END auto-facts -->", text, re.DOTALL)
    return m.group(1) if m else ""


def slashed(text):
    """Normalize path separators in captured output before matching.

    validate-okf.py reports file positions via os.path.relpath, so a finding
    reads `facts/m1.md:3` on POSIX and `facts\\m1.md:3` on Windows — as rules
    1-4 have always done. The assertion is about *which line* is reported, not
    about the separator, so normalize rather than hardcode either form."""
    return text.replace("\\", "/")


# The three modes, exactly as a model writes them.
MODE1 = "description: Angelo asked for help: the export was failing"
MODE2 = "description: Angelo asked for help in #suporte-produto about the export"
MODE3 = 'description: "Thayane took the informal role of "Chief Legal Officer", automating"'


# ---------------------------------------------------------------------------
# a. all three modes fail validation, localized
# ---------------------------------------------------------------------------

def test_three_modes_fail_validation(root):
    bundle = new_bundle(root, "three-modes")
    write_entity(bundle)
    for rel, line in (("facts/m1.md", MODE1), ("facts/m2.md", MODE2), ("facts/m3.md", MODE3)):
        write_fact(bundle, rel, line)

    r = run_script(bundle, "validate-okf.py")
    record("validate-okf.py exits nonzero when frontmatter is unsafe (it passed before rule 5)",
           r.returncode == 1, r.stdout + r.stderr)

    out = slashed(r.stdout)
    for rel, kind in (("m1", "`: `"), ("m2", "` #`"), ("m3", "unescaped inner quotes")):
        record(f"{rel}: reported on line 3 with the right diagnosis ({kind})",
               f"facts/{rel}.md:3: unsafe frontmatter `description`" in out
               and kind in out,
               r.stdout)

    record("the failure output points at --fix",
           "--fix" in r.stdout, r.stdout)


# ---------------------------------------------------------------------------
# b. safe shapes are not flagged — the check must not cry wolf
# ---------------------------------------------------------------------------

def test_safe_shapes_not_flagged(root):
    v = load_validator()
    safe = [
        ('quoted value containing `: `', 'description: "Angelo asked for help: the export failed"'),
        ('quoted value containing ` #`', 'description: "help in #suporte-produto about the export"'),
        ('single-quoted value containing "', "description: 'she said \"ship it\" on Friday'"),
        ('double-quoted value with escaped \\"', 'description: "she said \\"ship it\\" on Friday"'),
        ('`#` with no space before it', 'description: see ticket (#9-channel) for details'),
        ('trailing comment on an enum field', 'kind: concept        # person | org | project'),
        ('trailing comment containing `: `', 'channel: slack       # origin: slack:#channel'),
        ('a URL', 'resource: https://example.com/a/b'),
        ('an inline flow list', "entities: ['/entities/person/x.md', '/b.md']"),
        ('a block-sequence list', "entities:\n  - /entities/person/x.md"),
        # Regression: comment-stripping used to run BEFORE the quote analysis, so
        # a properly quoted non-free-text value containing ` #` was cut mid-string
        # and misreported as an unterminated quote — with no repair possible.
        # Found on a real bundle, not by the suite. Both lines are valid YAML.
        ('quoted non-free-text value containing ` #`',
         'resource: "Slack #team-a, #team-b, #support-bugs"'),
        ('quoted channel list with ` #`', 'channel: "slack:#a, #b"'),
        ('quoted value with ` #` AND a trailing comment',
         'resource: "Slack #team-a"   # where it came from'),
        # Leading characters that are NOT indicators when followed by non-space.
        # Over-flagging these would fire on ordinary prose and numbers.
        ('leading `-` (a negative number)', 'description: -5% growth in Q3'),
        ('leading `~`', 'description: ~2000 documents migrated'),
        ('leading `?`', 'description: ?unclear whether this shipped'),
        ('leading `:`', 'description: :shrug was the only reply'),
        ('a backtick NOT in first position', 'description: the `lexflow init` command'),
        # `-`/`?` open a token only when alone or followed by a space, so these
        # stay legitimate plain scalars. All verified accepted by PyYAML.
        ('leading `->`', 'description: -> handed off to the platform team'),
        ('leading `---`', 'description: --- separator in the pasted log'),
        ('leading `??`', 'description: ?? nobody knows who owns this'),
        ('leading `--` (a CLI flag)', 'description: --force was required'),
        # A lone `~` is the idiomatic YAML null: `confidence: ~` meaning "unset"
        # is intent, not damage. Flagging it would be a false positive.
        ('a lone `~` (explicit null)', 'confidence: ~'),
    ]
    for label, line in safe:
        found = v.unsafe_frontmatter(line + "\n")
        record(f"not flagged: {label}", not found, found)

    unsafe = [("unterminated quote", 'description: "never closed', "unterminated-quote"),
              ("`: ` on a non-free-text field", "owner: Jane: the lead", "unquoted-colon")]
    # A plain scalar may not start with a YAML indicator. Verified against
    # PyYAML: ` @ % * ! , > | all raise; `&` does NOT — it parses as an anchor
    # and silently drops the first word, so it belongs with ` #` in the
    # invisible-damage group. Found on a real bundle via a backticked command
    # name in a description, and the lexical scan has to model it because the
    # PyYAML backstop doesn't run where PyYAML is absent — including CI.
    unsafe += [(f"leading {c!r} on a plain scalar",
                f"description: {c}lexflow init generates a CLAUDE.md", "reserved-lead")
               for c in "`@%&*!,>|"]
    # `-` and `?` are indicators only when they open a token: alone, or followed
    # by a space. Both forms raise ScannerError and take the whole block with
    # them, and the lexical scan missed both — a gap CodeRabbit caught on #5.
    # `:` is the same shape, already covered by the `: `/trailing-`:` rule.
    unsafe += [("`- ` opening the value", "description: - handed off to Ana", "reserved-lead"),
               ("`? ` opening the value", "description: ? unclear who owns it", "reserved-lead"),
               ("a lone `-`", "description: -", "reserved-lead"),
               ("a lone `?`", "description: ?", "reserved-lead"),
               ("a lone `:`", "description: :", "unquoted-colon")]
    for label, line, kind in unsafe:
        found = v.unsafe_frontmatter(line + "\n")
        record(f"flagged: {label}", len(found) == 1 and found[0][2] == kind, found)

    # Every finding must carry a repairable value, or --fix leaves the bundle
    # permanently red. On a real bundle this was 34 of 445 findings.
    inferable = [
        ('outer quotes ARE the quoting (strip them)',
         'description: "she said "ship it" now"', 'she said "ship it" now'),
        ('leading quote is CONTENT — a quoted title opening a sentence',
         'description: "Search API - Nova Onda" meeting on 2026-05-26 with Angelo',
         '"Search API - Nova Onda" meeting on 2026-05-26 with Angelo'),
        ('never-closed quote is kept verbatim, not guessed away',
         'description: "never closed', '"never closed'),
        ('leading YAML indicator — quote the whole value, indicator included',
         'description: `lexflow init` generates a CLAUDE.md',
         '`lexflow init` generates a CLAUDE.md'),
        ('leading `&` — the silent one; the dropped first word is preserved',
         'description: &lexflow init generates a CLAUDE.md',
         '&lexflow init generates a CLAUDE.md'),
        ('`- ` opening the value — the dash is content, keep it',
         'description: - handed off to Ana', '- handed off to Ana'),
    ]
    for label, line, want in inferable:
        found = v.unsafe_frontmatter(line + "\n")
        got = found[0][3] if found else None
        record(f"--fix can infer: {label}", got == want, f"want={want!r}\ngot ={got!r}")


# ---------------------------------------------------------------------------
# c. the shipped templates are themselves safe
# ---------------------------------------------------------------------------

def test_shipped_templates_are_safe(root):
    v = load_validator()
    for path in sorted((ASSETS / "templates").glob("*.md")):
        m = FM_RE.match(path.read_text(encoding="utf-8"))
        if not m:
            continue
        found = v.unsafe_frontmatter(m.group(1))
        record(f"template {path.name} has no unsafe frontmatter scalar", not found, found)
        record(f"template {path.name} quotes its free-text `description`",
               re.search(r'^description: ["\']', m.group(1), re.MULTILINE) is not None,
               m.group(1))


# ---------------------------------------------------------------------------
# d. --fix repairs all three, preserving the author's text
# ---------------------------------------------------------------------------

def test_fix_repairs_and_preserves(root):
    bundle = new_bundle(root, "fix-repairs")
    write_entity(bundle)
    for rel, line in (("facts/m1.md", MODE1), ("facts/m2.md", MODE2), ("facts/m3.md", MODE3)):
        write_fact(bundle, rel, line)

    r = run_script(bundle, "validate-okf.py", ["--fix"])
    record("--fix repairs all three and exits 0",
           r.returncode == 0 and "Repaired 3 unsafe scalar(s) in 3 file(s)" in r.stdout,
           r.stdout + r.stderr)

    # The point of JSON-encoding the value: inner quotes survive instead of
    # being stripped, and the `#channel` is kept as the content it always was.
    expected = {
        "facts/m1.md": "Angelo asked for help: the export was failing",
        "facts/m2.md": "Angelo asked for help in #suporte-produto about the export",
        "facts/m3.md": 'Thayane took the informal role of "Chief Legal Officer", automating',
    }
    for rel, want in expected.items():
        block = FM_RE.match((bundle / "knowledge" / rel).read_text(encoding="utf-8")).group(1)
        got = None
        for ln in block.splitlines():
            if ln.startswith("description:"):
                got = json.loads(ln.split(":", 1)[1].strip())
        record(f"{rel}: repaired value is byte-identical to what the author wrote",
               got == want, f"want={want!r}\ngot ={got!r}")

    r2 = run_script(bundle, "validate-okf.py")
    record("the repaired bundle revalidates clean", r2.returncode == 0, r2.stdout + r2.stderr)


# ---------------------------------------------------------------------------
# e. end-to-end impact: hub backlinks and manifest descriptions
# ---------------------------------------------------------------------------

def test_end_to_end_hub_and_manifest(root):
    bundle = new_bundle(root, "end-to-end")
    write_entity(bundle)
    write_fact(bundle, "facts/m1.md", MODE1, occurred="2026-07-28")
    write_fact(bundle, "facts/m2.md", MODE2, occurred="2026-07-27")
    write_fact(bundle, "facts/m3.md", MODE3, occurred="2026-07-26")

    r = run_script(bundle, "build-index.py")
    if HAS_YAML:
        record("build-index.py names the unparseable files on stderr instead of falling back silently",
               "/facts/m1.md" in r.stderr and "/facts/m3.md" in r.stderr and "WARNING" in r.stderr,
               r.stderr)
    else:
        skip("build-index.py names the unparseable files on stderr",
             "needs PyYAML — without it nothing raises, so there is no per-file warning to emit")

    rows = manifest_rows(bundle)
    record("no literal-quote artifacts in manifest.jsonl (the reported grep signal)",
           all(not any(e.startswith("'") or e.startswith('"') for e in row["entities"])
               for row in rows),
           [row["entities"] for row in rows])

    block = auto_facts_block(bundle)
    linked = set(re.findall(r"\]\((/facts/[^)]+)\)", block))
    record("all three facts reach the entity hub's auto-facts block "
           "(52 of 53 hubs regenerated empty before this fix)",
           linked == {"/facts/m1.md", "/facts/m2.md", "/facts/m3.md"}, sorted(linked))

    truncated = [r_["desc"] for r_ in rows if r_["path"] == "/facts/m2.md"][0]
    if HAS_YAML:
        record("mode 2 is still truncated before repair (the silent one — motivates the check)",
               truncated == "Angelo asked for help in", truncated)
    else:
        skip("mode 2 is still truncated before repair",
             "needs PyYAML — the naive parser doesn't strip comments, so it never truncates")

    run_script(bundle, "validate-okf.py", ["--fix"])
    run_script(bundle, "build-index.py")
    after = {r_["path"]: r_["desc"] for r_ in manifest_rows(bundle)}
    record("after --fix + rebuild, mode 2's description is whole again",
           after["/facts/m2.md"] == "Angelo asked for help in #suporte-produto about the export",
           after.get("/facts/m2.md"))
    record("after --fix + rebuild, mode 3 keeps its inner quotes",
           after["/facts/m3.md"] ==
           'Thayane took the informal role of "Chief Legal Officer", automating',
           after.get("/facts/m3.md"))
    record("after --fix + rebuild, build-index.py emits no YAML warning",
           "not valid YAML" not in run_script(bundle, "build-index.py").stderr)


# ---------------------------------------------------------------------------
# f2. unquote(): what the naive parser makes of a properly quoted value
# ---------------------------------------------------------------------------

def test_unquote_round_trips_fix_output(root):
    """The fallback parser must read back exactly what `--fix` writes. --fix
    emits JSON-escaped values (`"she said \\"ship it\\""`), so without
    unescaping, every description on a machine lacking PyYAML would render with
    visible backslashes — a regression introduced BY the repair path."""
    for script in ("build-index.py", "briefing.py"):
        spec = importlib.util.spec_from_file_location(
            "uq_" + script.replace(".", "_"), ASSETS / "scripts" / script)
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        cases = [
            ('"/entities/person/x.md"', "/entities/person/x.md", "double-quoted link"),
            ("'/entities/person/x.md'", "/entities/person/x.md", "single-quoted link"),
            ('"Angelo asked for help: the export failed"',
             "Angelo asked for help: the export failed", "quoted value with a colon"),
            ('"she said \\"ship it\\" on Friday"', 'she said "ship it" on Friday',
             "escaped inner quotes (exactly what --fix writes)"),
            ("'she said \"ship it\"'", 'she said "ship it"', "single-quoted with inner quotes"),
            ("'it''s shipped'", "it's shipped", "single-quoted with doubled apostrophe"),
            ('"a back\\\\slash"', "a back\\slash", "escaped backslash"),
            ('"literal \\n stays literal"', "literal \\n stays literal",
             "non-quote escape passed through, not guessed at"),
            ("unquoted stays as-is", "unquoted stays as-is", "unquoted value untouched"),
            ('"mismatched\'', '"mismatched\'', "mismatched quotes left alone"),
        ]
        for raw, want, label in cases:
            got = mod.unquote(raw)
            record(f"{script}: unquote — {label}", got == want, f"want={want!r}\ngot ={got!r}")


# ---------------------------------------------------------------------------
# f. missing PyYAML warns instead of degrading quietly
# ---------------------------------------------------------------------------

def test_missing_pyyaml_warns(root):
    bundle = new_bundle(root, "no-pyyaml")
    write_entity(bundle)
    write_fact(bundle, "facts/m1.md", MODE1)

    for script in ("build-index.py", "briefing.py"):
        r = run_script(bundle, script, ["--days", "7"] if script == "briefing.py" else None,
                       block_yaml=True)
        record(f"{script}: warns on stderr when PyYAML is missing",
               "PyYAML is not installed" in r.stderr, r.stderr)
        record(f"{script}: still succeeds — the fallback stays a supported path",
               r.returncode == 0, r.stdout + r.stderr)

    # Bundle-wide variant: with no PyYAML every file takes the naive parser, so
    # unquote() is what keeps quoted links resolving at all.
    rows = manifest_rows(bundle)
    record("no-PyYAML rebuild leaves no literal-quote artifacts in manifest.jsonl",
           rows and all(e == ENTITY_LINK for row in rows for e in row["entities"]),
           [row["entities"] for row in rows])
    record("no-PyYAML rebuild reaches the hub's auto-facts block",
           "/facts/m1.md" in auto_facts_block(bundle), auto_facts_block(bundle))


def main():
    print("elephant-mem test_frontmatter — YAML-safe frontmatter (validate-okf rule 5)")
    print(f"python:   {sys.version.splitlines()[0]}")
    print(f"platform: {sys.platform}")
    print(f"PyYAML:   {'present' if HAS_YAML else 'ABSENT — a few PyYAML-specific checks will skip'}")
    print()

    scratch_root = Path(tempfile.mkdtemp(prefix="elephant-mem-test-frontmatter-"))
    print(f"scratch root: {scratch_root}\n")

    for fn in (
        test_three_modes_fail_validation,
        test_safe_shapes_not_flagged,
        test_shipped_templates_are_safe,
        test_fix_repairs_and_preserves,
        test_end_to_end_hub_and_manifest,
        test_unquote_round_trips_fix_output,
        test_missing_pyyaml_warns,
    ):
        guarded(fn, scratch_root)

    print()
    print("Summary")
    print("-------")
    n_pass = 0
    for label, passed in checks:
        if passed:
            n_pass += 1
        print(f"  {'PASS' if passed else 'FAIL':4s}  {label}")
    for label, why in skipped:
        print(f"  SKIP  {label} — {why}")
    total = len(checks)
    print(f"\n{n_pass}/{total} checks passed"
          + (f", {len(skipped)} skipped." if skipped else "."))
    shutil.rmtree(scratch_root, ignore_errors=True)
    return 0 if n_pass == total and total > 0 else 1


if __name__ == "__main__":
    sys.exit(main())
