#!/usr/bin/env python3
"""Targeted regression tests for the derived-surfaces pipeline in
plugin/assets/scripts/ — complements tests/smoke.py (end-to-end happy path)
by covering the specific bug fixes and new behavior below:

  1. Block-style YAML sequences (`entities:\n  - /a.md`) in frontmatter list
     fields, not just inline `entities: [/a.md]`.
  2. Auto-facts marker injection: an entity/source file created without the
     `<!-- BEGIN auto-facts -->` marker gets one appended instead of silently
     never receiving backlinks.
  3. Hub sharding: an entity/source referenced by more than `hub_max_facts`
     active facts keeps only the N most recent inline and moves the rest
     (older actives + all history) to a sibling `<slug>.facts-archive.md`.
  4. vocab.json: validate-okf.py WARNs (never fails) on out-of-vocab values,
     and build-index.py's status-set dispatch changes behavior when
     vocab.json declares a value the hardcoded fallback doesn't know about
     (loop_status "expired").

Pure stdlib, Python 3.10+, same scaffolding style as tests/smoke.py: every
check builds its own throwaway bundle under a tempdir and drives the shipped
scripts via subprocess (sys.executable) — no shell-outs, no third-party deps.

Exit code 0 only if every check below passes.
"""
import datetime
import importlib.util
import json
import shutil
import subprocess
import sys
import tempfile
import traceback
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
ASSETS = REPO_ROOT / "plugin" / "assets"

TODAY = datetime.date.today().isoformat()
MONTH = datetime.date.today().strftime("%Y-%m")

checks = []


def record(label, passed, detail=""):
    checks.append((label, passed))
    status = "PASS" if passed else "FAIL"
    print(f"[{len(checks):2d}] {status} — {label}")
    if detail and not passed:
        for ln in str(detail).splitlines():
            print(f"       {ln}")
    return passed


def run_script(bundle, script_name, args=None):
    script = bundle / "scripts" / script_name
    return subprocess.run(
        [sys.executable, str(script)] + (args or []),
        cwd=str(bundle), capture_output=True, text=True, encoding="utf-8",
    )


def new_bundle(root, name, with_vocab=False, hub_max_facts=None):
    """Minimal throwaway bundle: shipped scripts + a reserved log.md, nothing
    else — each test seeds only the knowledge/ files it needs."""
    bundle = root / name
    (bundle / "scripts").mkdir(parents=True, exist_ok=True)
    for f in ("build-index.py", "briefing.py", "validate-okf.py"):
        shutil.copy2(ASSETS / "scripts" / f, bundle / "scripts" / f)
    if with_vocab:
        shutil.copy2(ASSETS / "vocab.json", bundle / "vocab.json")
    if hub_max_facts is not None:
        (bundle / "elephant.json").write_text(
            json.dumps({"index": {"hub_max_facts": hub_max_facts}}) + "\n", encoding="utf-8"
        )
    (bundle / "knowledge").mkdir(parents=True, exist_ok=True)
    (bundle / "knowledge" / "log.md").write_text("# Log\n", encoding="utf-8")
    return bundle


MARKER = (
    "\n<!-- BEGIN auto-facts -->\n"
    "<!-- Regenerated by scripts/build-index.py — do not edit by hand. -->\n"
    "<!-- END auto-facts -->\n"
)


def write_entity(bundle, rel, title, kind="person", with_marker=True):
    text = (
        "---\n"
        "type: entity\n"
        f"kind: {kind}\n"
        f"title: {title}\n"
        f"description: {title}.\n"
        "aliases: []\n"
        "tags: []\n"
        f"created: {TODAY}\n"
        f"updated: {TODAY}\n"
        f"timestamp: {TODAY}\n"
        "---\n\n"
        f"{title} — test entity.\n"
        f"{MARKER if with_marker else ''}"
    )
    path = bundle / "knowledge" / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return path


def write_fact(bundle, rel, desc, entities_yaml, status="active", confidence="high", occurred=None):
    text = (
        "---\n"
        "type: fact\n"
        f"description: {desc}\n"
        f"{entities_yaml}"
        f"confidence: {confidence}\n"
        f"status: {status}\n"
        "tags: []\n"
        f"created: {TODAY}\n"
        f"updated: {TODAY}\n"
        f"timestamp: {TODAY}\n"
        f"occurred: {occurred or TODAY}\n"
        "---\n\n"
        f"{desc}\n"
    )
    path = bundle / "knowledge" / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return path


def write_open_loop(bundle, rel, desc, entities_yaml, status="open"):
    text = (
        "---\n"
        "type: open-loop\n"
        f"description: {desc}\n"
        f"{entities_yaml}"
        f"status: {status}\n"
        f"opened: {TODAY}\n"
        "tags: []\n"
        f"created: {TODAY}\n"
        f"updated: {TODAY}\n"
        f"timestamp: {TODAY}\n"
        "---\n\n"
        f"{desc}\n"
    )
    path = bundle / "knowledge" / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return path


def write_source(bundle, rel, desc, source_kind="note"):
    text = (
        "---\n"
        "type: source\n"
        f"description: {desc}\n"
        "resource: https://example.com/test\n"
        f"source-kind: {source_kind}\n"
        "channel: manual\n"
        f"occurred: {TODAY}\n"
        f"ingested: {TODAY}\n"
        "tags: []\n"
        f"created: {TODAY}\n"
        f"updated: {TODAY}\n"
        f"timestamp: {TODAY}\n"
        "---\n\n"
        f"{desc}\n"
        f"{MARKER}"
    )
    path = bundle / "knowledge" / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return path


def load_module_forcing_no_yaml(script_name):
    """Import a hyphenated script (build-index.py, briefing.py) as a module
    with its `yaml` global forced to None, so parse_fm() exercises the
    hand-rolled fallback regardless of whether PyYAML happens to be installed
    in the environment running these tests (it is on this dev machine, but
    NOT in CI — see .github/workflows/ci.yml — and presumably not in most
    bundle environments either, which is how the reported bug went unnoticed)."""
    path = ASSETS / "scripts" / script_name
    spec = importlib.util.spec_from_file_location(script_name.replace(".", "_"), path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    mod.yaml = None
    return mod


# ---------------------------------------------------------------------------
# 1a. block-style YAML sequences — direct unit test of the fallback parser
#     (forces yaml=None so it can't be masked by PyYAML being installed)
# ---------------------------------------------------------------------------

def test_parse_fm_fallback_block_lists(root):
    for script_name in ("build-index.py", "briefing.py"):
        mod = load_module_forcing_no_yaml(script_name)

        block = (
            "type: fact\n"
            "description: block-style entities\n"
            "entities:\n"
            "  - /entities/person/alice.md\n"
            "  - /entities/org/acme.md\n"
            "tags: []\n"
        )
        fm = mod.parse_fm(block)
        record(
            f"{script_name}: fallback parser reads a block-sequence list (entities:)",
            fm.get("entities") == ["/entities/person/alice.md", "/entities/org/acme.md"],
            fm,
        )

        inline_block = "entities: [/a.md, /b.md]\ntags: []\n"
        fm_inline = mod.parse_fm(inline_block)
        record(
            f"{script_name}: fallback parser still reads inline lists (regression guard)",
            fm_inline.get("entities") == ["/a.md", "/b.md"],
            fm_inline,
        )

        empty_block = "owner:\ntags: []\n"
        fm_empty = mod.parse_fm(empty_block)
        record(
            f"{script_name}: fallback parser leaves a genuinely empty list field as \"\" (not a crash)",
            fm_empty.get("owner") == "" and fm_empty.get("tags") == [],
            fm_empty,
        )

        nested_block = (
            "relations:\n"
            "  supersedes: []\n"
            "  superseded-by: []\n"
            "confidence: high\n"
        )
        fm_nested = mod.parse_fm(nested_block)
        record(
            f"{script_name}: fallback parser leaves a nested mapping (relations:) as \"\" "
            "(unsupported, unchanged from before this fix)",
            fm_nested.get("relations") == "" and fm_nested.get("confidence") == "high",
            fm_nested,
        )


# ---------------------------------------------------------------------------
# 1b. block-style YAML sequences — end-to-end via build-index.py
# ---------------------------------------------------------------------------

def test_block_style_entities(root):
    bundle = new_bundle(root, "block-style")
    write_entity(bundle, "entities/person/alice.md", "Alice")
    write_fact(
        bundle, "facts/f1.md", "Alice said hi",
        entities_yaml="entities:\n  - /entities/person/alice.md\n",
    )
    result = run_script(bundle, "build-index.py")
    if not record("build-index.py exits 0 (block-style entities)", result.returncode == 0,
                   result.stdout + result.stderr):
        return

    alice = (bundle / "knowledge" / "entities" / "person" / "alice.md").read_text(encoding="utf-8")
    record(
        "block-style `entities:` list produces a backlink into the entity file",
        "Alice said hi" in alice and "/facts/f1.md" in alice,
        alice,
    )

    manifest = (bundle / "knowledge" / "manifest.jsonl").read_text(encoding="utf-8")
    record(
        "fact with block-style entities still lands in manifest.jsonl with entities populated",
        '"entities":["/entities/person/alice.md"]' in manifest,
        manifest,
    )


# ---------------------------------------------------------------------------
# 2. auto-facts marker injection
# ---------------------------------------------------------------------------

def test_marker_injection(root):
    bundle = new_bundle(root, "marker-injection")
    write_entity(bundle, "entities/team/contexters.md", "Contexters", kind="team", with_marker=False)
    write_fact(
        bundle, "facts/f1.md", "Contexters shipped v1",
        entities_yaml="entities: [/entities/team/contexters.md]\n",
    )

    result = run_script(bundle, "build-index.py")
    if not record("build-index.py exits 0 (markerless entity)", result.returncode == 0,
                   result.stdout + result.stderr):
        return

    record(
        "logs one line for the markerless entity it injected a marker into",
        "Injected auto-facts marker: /entities/team/contexters.md" in result.stdout,
        result.stdout,
    )

    path = bundle / "knowledge" / "entities" / "team" / "contexters.md"
    text = path.read_text(encoding="utf-8")
    record(
        "marker appended + backlink filled on first run",
        text.count("<!-- BEGIN auto-facts -->") == 1 and "Contexters shipped v1" in text,
        text,
    )

    result2 = run_script(bundle, "build-index.py")
    text2 = path.read_text(encoding="utf-8")
    record(
        "rerun is idempotent: marker not duplicated, no re-injection log line",
        text2.count("<!-- BEGIN auto-facts -->") == 1
        and "Injected auto-facts marker" not in result2.stdout,
        result2.stdout + "\n---\n" + text2,
    )


# ---------------------------------------------------------------------------
# 3. hub sharding
# ---------------------------------------------------------------------------

def test_hub_sharding(root):
    bundle = new_bundle(root, "hub-sharding", hub_max_facts=3)
    write_entity(bundle, "entities/org/acme.md", "Acme")

    dates = ["2026-01-01", "2026-01-02", "2026-01-03", "2026-01-04", "2026-01-05"]
    for i, d in enumerate(dates, start=1):
        write_fact(
            bundle, f"facts/active-{i}.md", f"Acme active fact {i}",
            entities_yaml="entities: [/entities/org/acme.md]\n", occurred=d,
        )
    for i in (1, 2):
        write_fact(
            bundle, f"facts/history-{i}.md", f"Acme history fact {i}",
            entities_yaml="entities: [/entities/org/acme.md]\n",
            status="superseded", occurred=f"2025-12-0{i}",
        )

    result = run_script(bundle, "build-index.py")
    if not record("build-index.py exits 0 (7 refs on a hub_max_facts=3 hub)", result.returncode == 0,
                   result.stdout + result.stderr):
        return

    acme_path = bundle / "knowledge" / "entities" / "org" / "acme.md"
    acme = acme_path.read_text(encoding="utf-8")
    inline_kept = sum(f"Acme active fact {i}" in acme for i in range(1, 6))
    record("inline block keeps only hub_max_facts (3) active facts", inline_kept == 3, acme)
    record(
        "inline block keeps the 3 MOST RECENT active facts by `occurred` (3, 4, 5)",
        all(f"Acme active fact {i}" in acme for i in (3, 4, 5))
        and not any(f"Acme active fact {i}" in acme for i in (1, 2)),
        acme,
    )
    record("inline block drops its history section entirely once sharded",
           "Superseded / deprecated (history)" not in acme, acme)
    record("inline block ends with an archive link line",
           "facts-archive.md" in acme and "older/superseded facts" in acme, acme)

    archive_path = bundle / "knowledge" / "entities" / "org" / "acme.facts-archive.md"
    record("sibling archive file was created", archive_path.exists())
    if archive_path.exists():
        archive = archive_path.read_text(encoding="utf-8")
        record(
            "archive holds the 2 overflow actives + both history facts, none of the inline 3",
            all(f"Acme active fact {i}" in archive for i in (1, 2))
            and all(f"Acme history fact {i}" in archive for i in (1, 2))
            and not any(f"Acme active fact {i}" in archive for i in (3, 4, 5)),
            archive,
        )

    val = run_script(bundle, "validate-okf.py")
    record("validate-okf.py passes despite the frontmatter-less archive file",
           val.returncode == 0, val.stdout + val.stderr)

    before = archive_path.read_text(encoding="utf-8") if archive_path.exists() else None
    result2 = run_script(bundle, "build-index.py")
    after = archive_path.read_text(encoding="utf-8") if archive_path.exists() else None
    record("rebuild is idempotent: archive content unchanged across reruns",
           result2.returncode == 0 and before is not None and before == after,
           f"before={before!r}\nafter={after!r}")

    # shrink the hub back under the threshold -> stale archive must be removed
    for i in (1, 2):
        (bundle / "knowledge" / "facts" / f"active-{i}.md").unlink()
        (bundle / "knowledge" / "facts" / f"history-{i}.md").unlink()
    result3 = run_script(bundle, "build-index.py")
    record(
        "shrinking the hub below hub_max_facts removes the now-stale archive file",
        result3.returncode == 0 and not archive_path.exists(),
        result3.stdout + result3.stderr,
    )


# ---------------------------------------------------------------------------
# 4a. vocab.json — validate-okf.py WARNINGS (never errors)
# ---------------------------------------------------------------------------

def test_vocab_warnings(root):
    bundle = new_bundle(root, "vocab-warnings", with_vocab=True)
    write_entity(bundle, "entities/person/bob.md", "Bob", kind="alien")
    write_source(bundle, f"sources/{MONTH}/s1.md", "weird source", source_kind="rumor")

    val = run_script(bundle, "validate-okf.py")
    record("validate-okf.py still exits 0 — vocab issues are WARNINGS, never errors",
           val.returncode == 0, val.stdout + val.stderr)
    record("warns about out-of-vocab kind='alien' with a count",
           "out-of-vocab kind='alien' (1 file(s))" in val.stdout, val.stdout)
    record("warns about out-of-vocab source-kind='rumor' with a count",
           "out-of-vocab source-kind='rumor' (1 file(s))" in val.stdout, val.stdout)

    bundle2 = new_bundle(root, "vocab-absent", with_vocab=False)
    write_entity(bundle2, "entities/person/bob.md", "Bob", kind="alien")
    write_source(bundle2, f"sources/{MONTH}/s1.md", "weird source", source_kind="rumor")
    val2 = run_script(bundle2, "validate-okf.py")
    record(
        "without vocab.json, the same weird values are NOT flagged (vocab checks skipped entirely)",
        val2.returncode == 0 and "out-of-vocab" not in val2.stdout,
        val2.stdout,
    )


# ---------------------------------------------------------------------------
# 4b. vocab.json — build-index.py status-set dispatch changes with vocab.json
# ---------------------------------------------------------------------------

def _expired_loop_bundle(root, name, with_vocab):
    bundle = new_bundle(root, name, with_vocab=with_vocab)
    write_entity(bundle, "entities/person/carol.md", "Carol")
    write_open_loop(
        bundle, "tracking/loops/l1.md", "Carol's old commitment",
        entities_yaml="entities: [/entities/person/carol.md]\n",
        status="expired",
    )
    return bundle


def test_vocab_dispatch_expired_loop(root):
    bundle_absent = _expired_loop_bundle(root, "dispatch-absent", with_vocab=False)
    result_a = run_script(bundle_absent, "build-index.py")
    carol_a = (bundle_absent / "knowledge" / "entities" / "person" / "carol.md").read_text(encoding="utf-8")
    record("(no vocab.json) build-index.py exits 0", result_a.returncode == 0,
           result_a.stdout + result_a.stderr)
    record(
        "(no vocab.json) an 'expired' loop is NOT treated as history — matches pre-vocab behavior",
        "Carol's old commitment" in carol_a and "Superseded / deprecated (history)" not in carol_a,
        carol_a,
    )

    bundle_present = _expired_loop_bundle(root, "dispatch-present", with_vocab=True)
    result_b = run_script(bundle_present, "build-index.py")
    carol_b = (bundle_present / "knowledge" / "entities" / "person" / "carol.md").read_text(encoding="utf-8")
    record("(vocab.json present) build-index.py exits 0", result_b.returncode == 0,
           result_b.stdout + result_b.stderr)
    record(
        "(vocab.json present, loop_status includes 'expired') the loop moves to the history section",
        "Superseded / deprecated (history)" in carol_b and "Carol's old commitment" in carol_b,
        carol_b,
    )

    brief_a = run_script(bundle_absent, "briefing.py", ["--days", "3650"])
    brief_b = run_script(bundle_present, "briefing.py", ["--days", "3650"])
    record(
        "briefing.py runs clean with and without vocab.json (dispatch fallback-parity)",
        brief_a.returncode == 0 and brief_b.returncode == 0
        and "Carol's old commitment" in brief_a.stdout
        and "Carol's old commitment" in brief_b.stdout,
        f"absent:\n{brief_a.stdout}{brief_a.stderr}\npresent:\n{brief_b.stdout}{brief_b.stderr}",
    )


def guarded(fn, root):
    try:
        fn(root)
    except Exception:  # noqa: BLE001 - report and continue to the next check group
        record(f"{fn.__name__} raised an unexpected exception", False, traceback.format_exc())


def main():
    print("elephant-mem test_index — targeted regression tests")
    print(f"python:   {sys.version.splitlines()[0]}")
    print(f"platform: {sys.platform}")
    print()

    scratch_root = Path(tempfile.mkdtemp(prefix="elephant-mem-test-index-"))
    print(f"scratch root: {scratch_root}\n")

    for fn in (
        test_parse_fm_fallback_block_lists,
        test_block_style_entities,
        test_marker_injection,
        test_hub_sharding,
        test_vocab_warnings,
        test_vocab_dispatch_expired_loop,
    ):
        guarded(fn, scratch_root)

    print()
    print("Summary")
    print("-------")
    n_pass = 0
    for label, passed in checks:
        status = "PASS" if passed else "FAIL"
        if passed:
            n_pass += 1
        print(f"  {status:4s}  {label}")
    total = len(checks)
    print(f"\n{n_pass}/{total} checks passed.")
    shutil.rmtree(scratch_root, ignore_errors=True)
    return 0 if n_pass == total and total > 0 else 1


if __name__ == "__main__":
    sys.exit(main())
