#!/usr/bin/env python3
"""Operational state for the elephant `catch-up` routine.

Canonical machine state lives in `state/cursors.json` + `state/processed-events.json`.
`state/watermarks.md` is a human-readable rendering, regenerated on every
mutation (like the OKF derived files — do NOT hand-edit it). `state/` is NOT part
of the OKF bundle (not under `knowledge/`), so `validate-okf.py` never touches it.

Two cursors per channel:
  live_cursor      ISO datetime — newest content ingested; the forward routine
                   reads strictly *after* this. Advance only on a successful run.
  backfill_oldest  YYYY-MM-DD — how far back the day-by-day sweep has reached.
                   Pulled only when forward is caught up (forward-first policy).

Subcommands:
  show                                print the current state
  after <channel>                     print live_cursor as a Unix ts (Slack `after`)
  advance-live <channel> <iso>        set live_cursor (forward progress)
  advance-backfill <channel> <date>   set backfill_oldest (one older day done)
  set-last-run <channel> <iso>        stamp last_run
  mark <id> [<id>...]                 record processed calendar/Drive ids
  seen <id>                           exit 0 if id already processed, else 1
  next-backfill <channel>             print next older day to backfill, or NONE
  render                              rewrite watermarks.md
"""
import json
import sys
from datetime import datetime, timedelta
from pathlib import Path

STATE = Path(__file__).resolve().parent.parent / "state"
CURSORS = STATE / "cursors.json"
PROCESSED = STATE / "processed-events.json"
WATERMARKS = STATE / "watermarks.md"


def load(p):
    return json.loads(p.read_text(encoding="utf-8"))


def save(p, data):
    p.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def parse_iso(s):
    return datetime.fromisoformat(s)


def render(cur):
    lines = [
        "# Watermarks",
        "",
        "Operational cursors for the `elephant catch-up` routine. **Regenerated by",
        "`scripts/state.py` — do not hand-edit** (canonical state is `cursors.json`).",
        "Not part of the OKF bundle (not under `knowledge/`).",
        "",
        "- **live_cursor** — newest content already ingested; the forward routine",
        "  reads strictly *after* this and advances it. Timestamp-granular, so empty",
        "  runs are cheap and a partial day is never re-deduped.",
        "- **backfill_oldest** — how far back the day-by-day sweep has reached; pulled",
        "  only once forward is caught up (forward-first).",
        "",
        "| channel | live_cursor | backfill_oldest | last_run |",
        "|---------|-------------|-----------------|----------|",
    ]
    for name, c in cur["channels"].items():
        lines.append(
            f"| {name} | {c['live_cursor']} | {c['backfill_oldest']} | {c['last_run'] or '—'} |"
        )
    cfg = cur.get("config", {})
    lines += [
        "",
        f"Backfill window floor: **{cfg.get('backfill_window_start', '?')}** "
        f"(30-day horizon). gcal lag={cfg.get('gcal_lag_hours','?')}h, "
        f"lookback={cfg.get('gcal_lookback_hours','?')}h.",
        "",
        "Advance a cursor ONLY after a successful ingest + validate + commit.",
        "",
    ]
    WATERMARKS.write_text("\n".join(lines), encoding="utf-8")


def main(argv):
    if not argv:
        print(__doc__)
        return 0
    cmd, rest = argv[0], argv[1:]
    cur = load(CURSORS)
    chans = cur["channels"]
    cfg = cur.get("config", {})

    if cmd == "show":
        print(json.dumps(cur, indent=2, ensure_ascii=False))
    elif cmd == "after":
        ch = rest[0]
        print(int(parse_iso(chans[ch]["live_cursor"]).timestamp()))
    elif cmd == "advance-live":
        ch, iso = rest[0], rest[1]
        parse_iso(iso)  # validate
        chans[ch]["live_cursor"] = iso
        save(CURSORS, cur)
        render(cur)
        print(f"{ch} live_cursor -> {iso}")
    elif cmd == "advance-backfill":
        ch, date = rest[0], rest[1]
        datetime.strptime(date, "%Y-%m-%d")  # validate
        chans[ch]["backfill_oldest"] = date
        save(CURSORS, cur)
        render(cur)
        print(f"{ch} backfill_oldest -> {date}")
    elif cmd == "set-last-run":
        ch, iso = rest[0], rest[1]
        parse_iso(iso)
        chans[ch]["last_run"] = iso
        save(CURSORS, cur)
        render(cur)
        print(f"{ch} last_run -> {iso}")
    elif cmd == "mark":
        proc = load(PROCESSED)
        s = set(proc["processed"])
        before = len(s)
        s.update(rest)
        proc["processed"] = sorted(s)
        save(PROCESSED, proc)
        print(f"marked {len(s) - before} new ({len(s)} total)")
    elif cmd == "seen":
        proc = load(PROCESSED)
        return 0 if rest[0] in set(proc["processed"]) else 1
    elif cmd == "next-backfill":
        ch = rest[0]
        oldest = datetime.strptime(chans[ch]["backfill_oldest"], "%Y-%m-%d")
        nxt = oldest - timedelta(days=1)
        floor = datetime.strptime(cfg["backfill_window_start"], "%Y-%m-%d")
        print("NONE" if nxt < floor else nxt.strftime("%Y-%m-%d"))
    elif cmd == "render":
        render(cur)
        print("watermarks.md regenerated")
    else:
        print(f"unknown command: {cmd}", file=sys.stderr)
        print(__doc__, file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
